export { BasketPagesTemplate } from "./BasketPagesTemplate/BasketPagesTemplate";
export { BuyerRegistrationPageTemplate } from "./BuyerRegistrationPageTemplate/BuyerRegistrationPageTemplate";
export { LoginPageTemplate } from "./LoginPageTemplate/LoginPageTemplate";
export { NewsDetailsTemplate } from "./NewsDetailsTemplate/NewsDetailsTemplate";
export { ProductDetailsTemplate } from "./ProductDetailsTemplate/ProductDetailsTemplate";
export { ProductPageTemplate } from "./ProductPageTemplate/ProductPageTemplate";
export { SellerRegistrationPageTemplates } from "./SellerRegistrationPageTemplates/SellerRegistrationPageTemplates";
export { UsefulArticlesDetailTemplate } from "./UsefulArticlesDetailTemplate/UsefulArticlesDetailTemplate";
export { ProfileTemplate } from "./ProfileTemplate/ProfileTemplate";